# sure are a lot of things to just check line endings on
dos2unix -- ./*
dos2unix -- ./config/*
dos2unix -- ./config/*/*
dos2unix -- ./config/*/*/*
dos2unix -- ./config/*/*/*/*
dos2unix -- ./patchouli_books/*
dos2unix -- ./patchouli_books/*/*
dos2unix -- ./patchouli_books/*/*/*
dos2unix -- ./patchouli_books/*/*/*/*
dos2unix -- ./patchouli_books/*/*/*/*/*
dos2unix -- ./patchouli_books/*/*/*/*/*/*
dos2unix -- ./world/serverconfig/*
dos2unix -- ./world/serverconfig/*/*
dos2unix -- ./openloader/*
dos2unix -- ./openloader/*/*
dos2unix -- ./openloader/*/*/*
dos2unix -- ./openloader/*/*/*/*
dos2unix -- ./openloader/*/*/*/*/*
dos2unix -- ./openloader/*/*/*/*/*/*
