
#Mob Biome Config
#To filter biomes by registry name "mod_id:biome_id"
#To filter biomes by category "@category"
#To filter biomes by tags "#tag"
#	Examples:
#		"minecraft:plains"
#		"@desert"
#		"#overworld"
#
#If you want to exclude biomes put a ! before the biome identifier
#	Examples:
#		"!minecraft:plains"
#		"!@desert"
#		"!#nether"
#
#If you want to include biomes that would be satisfied by any in a set use |
#	Examples:
#		"|minecraft:plains"
#		"|@desert"
#		"|#nether"
#
#If you want a condition that MUST be satisfied use an & before the biome identifier
#Please note using this on a registry name wouldn't be that useful
#	Examples:
#		"&minecraft:plains"
#		"&@forest"
#		"&#overworld"
#
#NOTE: Any entry without a !, |, or & symbol has a higher precedence
#A list like ["!minecraft:plains", "#overworld"] would still see the plains as a viable biome
#
#Finally, you can create a expression that can be evaluated by itself using a + to combine identifiers
#	Examples:
#		"!#hot+!#dry+!#mountain"
#
#These expressions can be used to filter biomes in a lot of ways
#Lets say we don't want anything to spawn in any place dry and sandy
#	"!#dry+!#sandy"
#
#But there is a hot place we want them to spawn that's also wet
#	"#hot+#wet"
#
#We just put them as separate values in the list and that'll work out
#	["!#dry+!#sandy","#hot+#wet"]
#
#NOTE: Any entry that's an expression will not be affected by anything else in the list
[mob_biome_configs]
	UNWILLING = ["|#nether"]
	CYBER_DEMON_2016 = ["|#nether"]
	REVENANT = ["|#nether"]
	ZOMBIEMAN = ["|#nether"]
	CACODEMON = ["|#nether"]
	CHAINGUNNER = ["|#nether"]
	HELL_KNIGHT_2016 = ["|#nether"]
	LOST_SOUL = ["|#nether"]
	GARGOYLE = ["|#nether"]
	BARON = ["|#nether"]
	MANCUBUS = ["|#nether"]
	POSSESSED_SOLDIER = ["|#nether"]
	MECHA_ZOMBIE = ["|#nether"]
	ARCHVILE = ["|#nether"]
	IMP_2016 = ["|#nether"]
	NIGHTMARE_IMP = ["|#nether"]
	MARAUDER = ["|#nether"]
	GORE_NEST = ["|#nether"]
	PINKY = ["|#nether"]
	SPIDER_DEMON = ["|#nether"]
	IMP = ["|#nether"]
	HELL_KNIGHT = ["|#nether"]
	ARACHNOTRON = ["|#nether"]
	PAIN = ["|#nether"]
	CYBER_DEMON = ["|#nether"]
	SPECTRE = ["|#nether"]
	POSSESSED_SCIENTIST = ["|#nether"]
	SHOTGUN_GUY = ["|#nether"]

