
["Happy Trail Control Values"]
	#Debug Level: 0 = Off, 1 = Log, 2 = Chat+Log
	#Range: 0 ~ 2
	debugLevel = 0
	#Particles On: [true] / false
	particlesOn = true

["Trail Values 6464"]
	#Trail Block String 6464
	defaultTrailBlocksActual = "minecraft:bricks,11;minecraft:grass_path,2;minecraft:cave_air,4;mapperbase:asphalt,3;minecraft:stone_brick_slab,3;roadstuff:asphalt_slope,3;minecraft:sand,-1;"

