
#Emoji Rendering Settings
[Render]
	#Enables/Disables emoji rendering
	Enabled = true

#Text Suggestion Settings
[Suggest]
	#Enter key to suggest
	EnterToSuggest = true
	#Enables/Disables auto suggest
	Enabled = true

#Emoji Picker Settings
[Picker]
	#Emoji Picker Skin Tone
	SkinTone = 0

#Mod Update Checker
[Update]
	#Show Update Notification
	Notification = true

